In [18]:
import pandas as pd


# Read the CSV file into a DataFrame
df = pd.read_csv('label.csv')  # Assuming your CSV file is named 'MindPhix Dataset.csv'
df

,Depression level,Mood Level,Gender,Age Range,Category,Recommendation,Link
0,1,4,0,1,2,296,39
1,1,2,1,2,0,738,324
2,1,1,1,0,3,552,578
3,0,2,0,0,0,217,476
4,0,1,2,2,5,146,694
...,...,...,...,...,...,...,...
998,3,2,0,1,0,344,315
999,4,5,1,5,6,565,692
1000,1,3,2,4,7,440,242
1001,2,0,0,2,3,682,201
1002,0,4,1,3,1,50,170

In [17]:
y = df[['Recommendation', 'Link']]
y

      Recommendation  Link
0                296    39
1                738   324
2                552   578
3                217   476
4                146   694
...              ...   ...
998              344   315
999              565   692
1000             440   242
1001             682   201
1002              50   170

[1003 rows x 2 columns]

In [19]:
x = df[['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']]
x

      Depression level  Mood Level  Gender  Age Range  Category
0                    1           4       0          1         2
1                    1           2       1          2         0
2                    1           1       1          0         3
3                    0           2       0          0         0
4                    0           1       2          2         5
...                ...         ...     ...        ...       ...
998                  3           2       0          1         0
999                  4           5       1          5         6
1000                 1           3       2          4         7
1001                 2           0       0          2         3
1002                 0           4       1          3         1

[1003 rows x 5 columns]

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test, = train_test_split(x, y, test_size=0.2, random_state=100)

In [21]:
x_train

     Depression level  Mood Level  Gender  Age Range  Category
358                 4           3       2          2         6
159                 3           4       2          5         1
533                 0           4       2          3         1
680                 3           2       1          5         6
671                 2           5       0          1         4
..                ...         ...     ...        ...       ...
855                 0           4       2          0         1
871                 2           4       0          5         7
835                 0           4       1          2         3
792                 0           0       0          5         4
520                 2           3       0          0         4

[802 rows x 5 columns]

In [22]:
x_test

     Depression level  Mood Level  Gender  Age Range  Category
249                 0           5       2          1         3
353                 1           1       1          2         5
537                 1           1       0          2         3
424                 2           0       1          2         0
564                 1           4       0          0         4
..                ...         ...     ...        ...       ...
645                 3           6       2          2         6
110                 1           3       1          0         0
28                  1           0       0          2         1
936                 2           4       1          3         7
861                 1           0       2          0         4

[201 rows x 5 columns]

In [41]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

rf = RandomForestRegressor(max_depth=2, random_state=100)
rf.fit(x_train, y_train)

RandomForestRegressor(max_depth=2, random_state=100)

In [42]:
y_rf_train_pred = rf.predict(x_train)
y_rf_test_pred = rf.predict(x_test)

In [43]:
y_rf_train_pred

array([[409.88471423, 208.20652059],
       [417.02517196, 461.23075461],
       [417.02517196, 461.23075461],
       ...,
       [435.3457452 , 378.22707637],
       [411.78239295, 367.52492966],
       [414.670103  , 364.75567463]])

In [44]:
y_rf_test_pred

array([[435.3457452 , 378.22707637],
       [409.47144111, 216.50277643],
       [434.58891921, 379.08468957],
       [395.72043819, 485.85656363],
       [412.46203986, 367.68293519],
       [416.62436558, 466.82442751],
       [411.91466013, 465.99291645],
       [417.02517196, 461.23075461],
       [434.58891921, 379.08468957],
       [409.02513238, 468.19444901],
       [414.38080913, 365.4870109 ],
       [434.59581499, 218.25460971],
       [415.13763513, 364.6293977 ],
       [413.46350381, 471.04544555],
       [435.3457452 , 378.22707637],
       [412.06022658, 468.1438136 ],
       [417.34569827, 361.70213714],
       [406.82306815, 475.54976406],
       [415.60083437, 462.97239382],
       [434.27887803, 217.33239857],
       [411.68595739, 208.54950456],
       [410.88196279, 206.70075007],
       [416.38578639, 463.17702278],
       [431.99050303, 381.12260833],
       [399.40661242, 482.836041  ],
       [416.62436558, 466.82442751],
       [414.74728209, 363.74005591],
       [409.77732957, 474.06596819],
       [425.59943745, 236.31717191],
       [435.3457452 , 378.22707637],
       [410.36749429, 233.16792084],
       [409.47144111, 216.50277643],
       [412.12496025, 468.86155028],
       [407.67019795, 216.15979247],
       [414.38080913, 365.4870109 ],
       [415.13763513, 364.6293977 ],
       [435.3457452 , 378.22707637],
       [412.46203986, 367.68293519],
       [418.10252426, 360.84452394],
       [411.91466013, 465.99291645],
       [417.02517196, 461.23075461],
       [417.34569827, 361.70213714],
       [420.37068786, 226.34010427],
       [414.38080913, 365.4870109 ],
       [412.46203986, 367.68293519],
       [411.78239295, 367.52492966],
       [416.24021994, 461.02612564],
       [448.23751292, 214.42292256],
       [435.3457452 , 378.22707637],
       [422.58520414, 218.3868324 ],
       [411.70521386, 368.54054839],
       [411.78239295, 367.52492966],
       [412.69961215, 466.19754542],
       [417.02517196, 461.23075461],
       [434.6660983 , 378.06907084],
       [416.24021994, 461.02612564],
       [410.36749429, 233.16792084],
       [414.10288938, 469.09917737],
       [413.46350381, 471.04544555],
       [448.55444988, 215.34513369],
       [395.72043819, 485.85656363],
       [411.04780589, 230.73993917],
       [416.38578639, 463.17702278],
       [435.3457452 , 378.22707637],
       [414.10288938, 469.09917737],
       [414.10288938, 469.09917737],
       [411.91466013, 465.99291645],
       [434.58891921, 379.08468957],
       [434.58891921, 379.08468957],
       [435.3457452 , 378.22707637],
       [446.02299664, 222.37619443],
       [448.72029299, 239.3843228 ],
       [448.23751292, 214.42292256],
       [438.09710593, 237.11149258],
       [431.99050303, 381.12260833],
       [415.13763513, 364.6293977 ],
       [417.02517196, 461.23075461],
       [416.24021994, 461.02612564],
       [420.37068786, 226.34010427],
       [412.69961215, 466.19754542],
       [412.67855179, 470.84081659],
       [415.13763513, 364.6293977 ],
       [409.98392993, 471.32874602],
       [409.34454435, 473.2750142 ],
       [411.91466013, 465.99291645],
       [409.34454435, 473.2750142 ],
       [435.3457452 , 378.22707637],
       [417.02517196, 461.23075461],
       [409.17069883, 470.34534615],
       [448.84831585, 242.20737238],
       [410.88196279, 206.70075007],
       [434.27887803, 217.33239857],
       [435.3457452 , 378.22707637],
       [413.39034504, 225.60971688],
       [412.67855179, 470.84081659],
       [416.38578639, 463.17702278],
       [408.55959233, 473.07038523],
       [414.670103  , 364.75567463],
       [412.00289435, 209.4717157 ],
       [417.02517196, 461.23075461],
       [406.82306815, 475.54976406],
       [409.10679768, 370.57846715],
       [422.58520414, 218.3868324 ],
       [415.13763513, 364.6293977 ],
       [437.55380834, 375.29981581],
       [420.37068786, 226.34010427],
       [412.16873745, 233.51090481],
       [414.74728209, 363.74005591],
       [411.78239295, 367.52492966],
       [413.39034504, 225.60971688],
       [422.58520414, 218.3868324 ],
       [410.88196279, 206.70075007],
       [415.60083437, 462.97239382],
       [413.26232217, 222.7866673 ],
       [409.8100844 , 468.39907797],
       [414.7001907 , 226.47984407],
       [414.10288938, 469.09917737],
       [417.34569827, 361.70213714],
       [412.58201057, 225.21464897],
       [409.77732957, 474.06596819],
       [409.19897791, 471.12411705],
       [434.6660983 , 378.06907084],
       [410.38473631, 465.73507312],
       [438.31063433, 374.44220261],
       [411.68595739, 208.54950456],
       [414.38325373, 225.55763293],
       [412.67855179, 470.84081659],
       [415.60083437, 462.97239382],
       [434.72383786, 221.07765929],
       [412.29880577, 471.79121832],
       [446.02299664, 222.37619443],
       [414.670103  , 364.75567463],
       [440.22940361, 372.24627832],
       [400.04599799, 480.88977282],
       [418.10252426, 360.84452394],
       [415.13763513, 364.6293977 ],
       [412.89894754, 226.13686011],
       [413.26232217, 222.7866673 ],
       [409.19897791, 471.12411705],
       [410.56502583, 205.77853893],
       [394.29610059, 487.59820285],
       [448.55444988, 215.34513369],
       [411.91466013, 465.99291645],
       [411.68595739, 208.54950456],
       [413.46350381, 471.04544555],
       [440.22940361, 372.24627832],
       [410.38473631, 465.73507312],
       [410.38473631, 465.73507312],
       [415.60083437, 462.97239382],
       [434.88968096, 245.1168484 ],
       [410.56502583, 205.77853893],
       [411.70521386, 368.54054839],
       [412.07168682, 366.79359339],
       [431.99050303, 381.12260833],
       [410.38473631, 465.73507312],
       [412.06022658, 468.1438136 ],
       [410.56502583, 205.77853893],
       [414.38080913, 365.4870109 ],
       [434.08134649, 244.72178048],
       [422.58520414, 218.3868324 ],
       [392.62061032, 485.18946236],
       [416.45052006, 463.89475946],
       [411.78239295, 367.52492966],
       [414.10288938, 469.09917737],
       [410.36749429, 233.16792084],
       [410.56502583, 205.77853893],
       [413.31793736, 468.89454841],
       [434.08134649, 244.72178048],
       [409.98392993, 471.32874602],
       [408.35050955, 213.7318108 ],
       [409.47144111, 216.50277643],
       [432.19238461, 228.10872002],
       [412.07168682, 366.79359339],
       [434.27887803, 217.33239857],
       [414.74728209, 363.74005591],
       [414.10288938, 469.09917737],
       [434.58891921, 379.08468957],
       [438.02134047, 375.17353888],
       [411.70521386, 368.54054839],
       [409.19897791, 471.12411705],
       [410.36749429, 233.16792084],
       [435.3457452 , 378.22707637],
       [408.35050955, 213.7318108 ],
       [409.98392993, 471.32874602],
       [434.08134649, 244.72178048],
       [415.42692899, 363.89806143],
       [422.58520414, 218.3868324 ],
       [422.58520414, 218.3868324 ],
       [410.87446818, 473.53285753],
       [448.55444988, 215.34513369],
       [409.19897791, 471.12411705],
       [414.10288938, 469.09917737],
       [409.98392993, 471.32874602],
       [399.40661242, 482.836041  ],
       [449.35844448, 217.19388819],
       [409.02513238, 468.19444901],
       [410.56502583, 205.77853893],
       [409.8100844 , 468.39907797],
       [394.93548617, 485.65193467],
       [413.57925914, 223.70887844],
       [409.10679768, 370.57846715]])

In [45]:
from sklearn.metrics import mean_squared_error, r2_score

rf_train_mse = mean_squared_error(y_train, y_rf_train_pred)
rf_train_r2 = r2_score(y_train, y_rf_train_pred)

rf_test_mse = mean_squared_error(y_test, y_rf_test_pred)
rf_test_r2 = r2_score(y_test, y_rf_test_pred)

In [30]:
rf_train_msc

15287.519448655872

In [31]:
rf_test_msc

56692.44377953891

In [32]:
rf_train_r2

0.7197453031657517

In [33]:
rf_test_r2

-0.03214618531618019

In [48]:
rf_results = pd.DataFrame(['RandomForest', rf_train_mse, rf_train_r2, rf_test_mse, rf_test_r2]).transpose()
rf_results.columns = ['Method', 'Training MSE', 'Training R2', 'Test MSE', 'Test R2']

In [49]:
rf_results

         Method  Training MSE Training R2      Test MSE  Test R2
0  RandomForest  46510.418403    0.140043  46916.047751  0.14302

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score
#from sklearn.metrics import accuracy_score


# Read the CSV file into a DataFrame
df = pd.read_csv('label.csv')  # Assuming your CSV file is named 'MindPhix Dataset.csv'

# split the data
y = df[['Recommendation', 'Link']]
x = df[['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# build the model
dt = DecisionTreeRegressor(max_depth=2, random_state=100)
dt.fit(x_train, y_train)

y_dt_train_pred = dt.predict(x_train)
y_dt_test_pred = dt.predict(x_test)


# evaluate model performance
dt_train_mse = mean_squared_error(y_train, y_dt_train_pred)
dt_train_r2 = r2_score(y_train, y_dt_train_pred)

dt_test_mse = mean_squared_error(y_test, y_dt_test_pred)
dt_test_r2 = r2_score(y_test, y_dt_test_pred)

dt_results = pd.DataFrame(['DecisionTree', dt_train_mse, dt_train_r2, dt_test_mse, dt_test_r2]).transpose()
dt_results.columns = ['Method', 'Training MSE', 'Training R2', 'Test MSE', 'Test R2']

dt_results

#accueacy

#accuracy = accuracy_score(y_test, y_dt_test_pred )
#print(f'Accuracy: {accuracy*100:.2f}%')

         Method  Training MSE Training R2    Test MSE   Test R2
0  DecisionTree  47072.435105    0.129577  47144.5477  0.139027

In [62]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Read the CSV file into a DataFrame
df = pd.read_csv('label.csv')  # Assuming your CSV file is named 'label.csv'

# Split the data
y = df[['Recommendation', 'Link']]
x = df[['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Build the model
rf = RandomForestRegressor(max_depth=2, random_state=100)
rf.fit(x_train, y_train)

# Prompt user for input
depression_level = float(input("Enter Depression level: "))
mood_level = float(input("Enter Mood Level: "))
gender = input("Enter Gender (Male/Female): ")
age_range = input("Enter Age Range (e.g., 20-30): ")
category = input("Enter Category: ")

# Create a DataFrame with the user input
user_input_df = pd.DataFrame({
    'Depression level': [depression_level],
    'Mood Level': [mood_level],
    'Gender': [gender],
    'Age Range': [age_range],
    'Category': [category]
})

# Make prediction
predicted_recommendation, predicted_link = rf.predict(user_input_df).flatten()

# Print the predicted recommendation and link
print("Predicted Recommendation:", predicted_recommendation)
print("Predicted Link:", predicted_link)

Enter input in the format: Depression_Level Neutral Female 20-24 Motivational_Videos: https://insighttimer.com/spikegillespie/guided-meditations/intro-how-meditation-helped-me-with-depression

ValueError: not enough values to unpack (expected 5, got 1)

In [85]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Read the CSV file into a DataFrame
df = pd.read_csv('label.csv')  # Assuming your CSV file is named 'MindPhix Dataset.csv'

# Split the data
y = df['Recommendation']  # Considering 'Recommendation' as the target variable for classification
x = df[['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Build the model
dt = DecisionTreeClassifier(max_depth=2, random_state=100)
dt.fit(x_train, y_train)

# Predict on training and testing data
y_dt_train_pred = dt.predict(x_train)
y_dt_test_pred = dt.predict(x_test)

# Evaluate model performance
accuracy_train = accuracy_score(y_train, y_dt_train_pred)
accuracy_test = accuracy_score(y_test, y_dt_test_pred)

print(f'Training Accuracy: {accuracy_train*100:.2f}%')
print(f'Test Accuracy: {accuracy_test*100:.2f}%')

Training Accuracy: 2.49%
Test Accuracy: 0.50%

In [87]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Read the CSV file into a DataFrame
df = pd.read_csv('label.csv')  # Assuming your CSV file is named 'MindPhix Dataset.csv'

# Split the data
y = df['Recommendation']  # Considering 'Recommendation' as the target variable for classification
x = df[['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Build the model
dt = RandomForestClassifier(max_depth=2, random_state=100)
dt.fit(x_train, y_train)

# Predict on training and testing data
y_dt_train_pred = dt.predict(x_train)
y_dt_test_pred = dt.predict(x_test)

# Evaluate model performance
accuracy_train = accuracy_score(y_train, y_dt_train_pred)
accuracy_test = accuracy_score(y_test, y_dt_test_pred)

print(f'Training Accuracy: {accuracy_train*100:.2f}%')
print(f'Test Accuracy: {accuracy_test*100:.2f}%')

Training Accuracy: 8.23%
Test Accuracy: 1.00%

In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Read the CSV file into a DataFrame
df = pd.read_csv('newencode.csv')

# Combine 'Recommendation' and 'Link' columns into a single target variable
df['Target'] = df['Recommendation'] + ' | ' + df['Link']

# Define feature columns and target column
feature_columns = ['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']
target_column = 'Target'

# Split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(df[feature_columns], df[target_column], test_size=0.2, random_state=15)

# Train a decision tree classifier
clf = RandomForestClassifier().fit(x_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Assume user_inputs is a dictionary containing input values for the features
user_inputs = {'Depression level': 3, 'Mood Level': 2, 'Gender': 1, 'Age Range': 3, 'Category': 6}

# Create a DataFrame with the user's input
user_df = pd.DataFrame([user_inputs])

# Ensure column order and structure matches the training data
user_df = user_df.reindex(columns=feature_columns, fill_value=0)

# Use the trained model to predict recommendation
user_pred = clf.predict(user_df)

# Display the predicted recommendation
recommendation, link = prediction.split(' | ')

print("Recommendation:", recommendation)
print("Link:", link)

Accuracy: 3.48%
Recommendation: Letting Go of Anxiety meditation
Link: https://www.youtube.com/watch?v=6arfMc9Aj4k

In [4]:
# Import Statements
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
#%%
# Loading the dataset
df = pd.read_csv('MindPhix Sorted Dataset New.csv')

#Data Preprocessing 

# Ordinal Encoding - Depression Level and Age Range
depression_level = ['Minimal', 'Mild', 'Moderate', 'Moderately Severe', 'Severe']
enc = OrdinalEncoder(categories=[depression_level])
encoded_levels = enc.fit_transform(df[['Depression level']])
df['Depression level'] = encoded_levels

age_ranges = ['15-19', '20-24', '25-34', '35-44', '45-54', '55-65']
enc2 = OrdinalEncoder(categories=[age_ranges])
encoded_ages = enc2.fit_transform(df[['Age Range']])
df['Age Range'] = encoded_ages
df.head(10)

# Label Encoding 
# List of categorical columns to encode
categorical_cols = ['Mood Level', 'Gender', 'Category']

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Iterate over the categorical columns and apply label encoding
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])
    
df    

# Combine 'Recommendation' and 'Link' columns into a single target variable
df['Target'] = df['Recommendation'] + ' | ' + df['Link']

# Define feature columns and target column
feature_columns = ['Depression level', 'Mood Level', 'Gender', 'Age Range', 'Category']
target_column = 'Target'

# Split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(df[feature_columns], df[target_column], test_size=0.2, random_state=15)

#Training the dataset using Random Forest Classifier Algorithm 

# Train a decision tree classifier
clf = RandomForestClassifier().fit(x_train, y_train)

# Make predictions on the test set
y_prediction = clf.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_prediction)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Assume user_inputs is a dictionary containing input values for the features
user_inputs = {'Depression level':1, 'Mood Level': 1, 'Gender': 1, 'Age Range': 1, 'Category': 1}

# Create a DataFrame with the user's input
user_df = pd.DataFrame([user_inputs])

# Ensure column order and structure matches the training data
user_df = user_df.reindex(columns=feature_columns, fill_value=0)

# Use the trained model to predict recommendation
user_prediction = clf.predict(user_df)

# Print the predicted recommendation and link
prediction = user_prediction[0]

recommendation, link = prediction.split(' | ')

print("Recommendation:", recommendation)
print("Link:", link)

Accuracy: 17.54%
Recommendation: Breathing exercises for anxiety
Link: https://www.youtube.com/watch?v=AeMckI_nfP4